### ISSUE TITLE
Harfbuzz version too old (1.3.1) Error

### ISSUE THREAD

**Issue by Thai07** [cerebroapp/cerebro#534] opened 2021-06-12 12:35 UTC
![image](https://user-images.githubusercontent.com/61286182/121776100-c1fac400-cb93-11eb-8e34-13182c0c5f45.png)

**Comment by skyf0cker** [comment] 2021-06-22 15:23
Can you provide more details, e.g. what commands did you use?
@Thai07

**Comment by hwiorn** [comment] 2021-06-23 03:24
Duplicated #527.

@Thai07, What is your cerebro version?

**Comment by Blackrucat** [comment] 2021-06-23 17:40
**miau@pop-os:~$ cerebro**
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/miau/.config/Cerebro/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.get (/opt/Cerebro/resources/app.asar/main.js:162:18)
    at Object.module.exports.Object.defineProperty.value (/opt/Cerebro/resources/app.asar/main.js:642:24)
    at __webpack_require__ (/opt/Cerebro/resources/app.asar/main.js:21:30)
    at /opt/Cerebro/resources/app.asar/main.js:64:18
    at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:67:10)
    at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:3738:3)
    at Module._compile (module.js:571:32)

(cerebro:367894): Pango-ERROR **: 14:31:16.074: Harfbuzz version too old (1.3.1)

Trace/breakpoint trap (imagem do núcleo gravada)
```

pango version: 0.3.2

**Comment by hwiorn** [comment] 2021-06-24 05:01
You need a latest version. But the maintainer didn't release a v0.4.0 yet (#530).

**Comment by dubisdev** [comment] 2022-09-13 10:16
I'm closing this as a duplicate of #527

**Closed by dubisdev** 2022-09-13 10:16 UTC
