### ISSUE TITLE
I have cerebro on two pc win 10, the problem is that on the notebook when i trigger cerebro it doesn't close automatically if it lose the focus, Instead on the other pc it has this behaviours. some hint?

### ISSUE THREAD

**Issue by draugvar** [cerebroapp/cerebro#388] opened 2017-09-13 08:13 UTC
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Cerebro.app version**: 
- **Relevant information from devtools** _(See above how to open it)_:

**Comment by maximbaz** [comment] 2017-09-13 10:38
Type "Settings" and make sure "Developer mode" is disabled on both laptops.

**Comment by draugvar** [comment] 2017-09-13 12:56
yeah it is disabled but the problem persist.

**Comment by KELiON** [comment] 2017-10-11 07:45
@draugvar can you double check that you use latest version on both computers?

**Comment by draugvar** [comment] 2017-10-11 08:03
Yes it's the latest version




Get Outlook for Android







On Wed, Oct 11, 2017 at 9:46 AM +0200, "Alexandr Subbotin" <notifications@github.com> wrote:












@draugvar can you double check that you use latest version on both computers?

**Comment by rodrigomaia17** [comment] 2017-11-30 16:44
I'm getting the same issue on a macbook. If I open cerebro, and then move focus to another app (like alt-tabbing), then the cerebro search keeps on top of everything until I click on it and then close it.

**Comment by lawgsy** [comment] 2017-12-03 13:12
Can you please post the exact version number of Cerebro so we do not start miscommunicating? You can check by just typing `version` into cerebro.

I cannot reproduce this on the latest version of Cerebro (Cerebro 0.3.1, Windows 10).

Can you verify once more that under `Settings` (or `Preferences` as it is called in the taskbar menu) that `Developer mode` is unchecked?
1. **Is it checked?**
   - Uncheck it, now Cerebro **should** hide upon blur/unfocus
2. **Is it unchecked?**
   - Check it
   - Move focus to another application / hide cerebro
   - Open the settings again
   - Uncheck it once more, to ensure the change has registered

This shouldn't be necessary, but hey, who knows.

Does the problem persist?

**Comment by lawgsy** [comment] 2017-12-03 14:18
Related: https://github.com/KELiON/cerebro/issues/388

**Comment by rodrigomaia17** [comment] 2017-12-06 16:54
I've updated my app from 0.3.0 to 0.3.2 and it is fixed now. Thank you @lawgsy

**Comment by dubisdev** [comment] 2022-09-13 10:29
we are moving this issue to #391

**Closed by dubisdev** 2022-09-13 10:29 UTC
