### ISSUE TITLE
It's seems that the dependencies are too old and the package is so big

### ISSUE THREAD

**Issue by lyandzao** [cerebroapp/cerebro#501] opened 2020-03-03 14:45 UTC

**Comment by bwoodruff** [comment] 2020-03-07 23:17
Same experience here.

* Fedora 31
* Gnome 3 (latest stable)

<details><summary>debug info</summary>

```
$ ./cerebro-0.3.1-x86_64.AppImage 
installed: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9 image: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9

(cerebro:6798): Pango-ERROR **: 18:12:30.436: Harfbuzz version too old (1.3.1)

Trace/breakpoint trap (core dumped)
```

```
$ coredumpctl info
           PID: 6798 (cerebro)
           UID: 1000 (bdw)
           GID: 1000 (bdw)
        Signal: 5 (TRAP)
     Timestamp: Sat 2020-03-07 18:12:30 EST (1min 15s ago)
  Command Line: /tmp/.mount_uS6DAf/usr/bin/cerebro
    Executable: /tmp/.mount_uS6DAf/usr/bin/cerebro
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (bdw)
       Boot ID: 9b30662a8032426a926bb7ba5a954f6b
    Machine ID: 425fe6c0cdb540fd8ae56cd03bd9cf01
      Hostname: bwx1l
       Storage: /var/lib/systemd/coredump/core.cerebro.1000.9b30662a8032426a926bb7ba5a954f6>
       Message: Process 6798 (cerebro) of user 1000 dumped core.
                
                Stack trace of thread 6798:
                #0  0x00007ff3733c8765 _g_log_abort (libglib-2.0.so.0)
                #1  0x00007ff3733cb13c g_log_writer_default (libglib-2.0.so.0)
                #2  0x00007ff3733c93a7 g_log_structured_array (libglib-2.0.so.0)
                #3  0x00007ff3733c9dc4 g_log_structured_standard (libglib-2.0.so.0)
                #4  0x00007ff3723ff591 pango_fc_font_map_get_hb_face (libpangoft2-1.0.so.0)
                #5  0x00007ff3723fa92e pango_fc_font_create_hb_font (libpangoft2-1.0.so.0)
                #6  0x00007ff373e95103 pango_font_get_hb_font (libpango-1.0.so.0)
                #7  0x00007ff373eaf743 pango_hb_shape (libpango-1.0.so.0)
                #8  0x00007ff373eaef9a pango_shape_with_flags (libpango-1.0.so.0)
                #9  0x00007ff373e9fc93 shape_run (libpango-1.0.so.0)
                #10 0x00007ff373ea20f8 process_item (libpango-1.0.so.0)
                #11 0x00007ff373ea429d pango_layout_check_lines (libpango-1.0.so.0)
                #12 0x00007ff373ea537e pango_layout_get_unknown_glyphs_count (libpango-1.0.>
                #13 0x00007ff3743c96b2 find_invisible_char (libgtk-x11-2.0.so.0)
                #14 0x00007ff3743cc937 gtk_entry_init (libgtk-x11-2.0.so.0)
                #15 0x00007ff373d4d1b1 g_type_create_instance (libgobject-2.0.so.0)
                #16 0x00007ff373d2f3f5 g_object_new_internal (libgobject-2.0.so.0)
                #17 0x00007ff373d30b05 g_object_new_with_properties (libgobject-2.0.so.0)
                #18 0x00007ff373d316b1 g_object_new (libgobject-2.0.so.0)
                #19 0x0000000002889482 n/a (/tmp/.mount_uS6DAf/usr/bin/cerebro)
```
</details>

**Comment by markboston3502191** [comment] 2020-05-21 18:49
is this even in development anymore?

**Comment by MartinArens** [comment] 2020-12-02 11:50
Same Issue

**Comment by dubisdev** [comment] 2022-09-13 10:17
I'm closing this as a duplicate of #527

**Closed by dubisdev** 2022-09-13 10:17 UTC
