### ISSUE TITLE
Cannot search for file names, needs full path!

### ISSUE THREAD

**Issue by Spandan-Madan** [cerebroapp/cerebro#475] opened 2018-09-10 19:42 UTC
So, I can't search for a file until I enter the full path? That sort of defeats the purpose of file search, right?

Currently, if there's a file on the desktop called text_file.txt, to search for it I have to search for ~/Desktop/text_file.txt, I can't directly search for text_file.txt. Is this correct, or do I have to change the settings to make the latter work?

Because otherwise currently this is basically useless for searching files.

**Comment by Mar-tin-W** [comment] 2018-12-26 13:58
I'm on a Linux machine with Cerebro v0.3.1 and have the same problem. 
It used to work on version 3.2.0 (I guess) but it stopped working after a reboot (i got a javascript error) so I decided to install v0.3.1.

you can get v0.3.2 here: https://github.com/KELiON/cerebro/releases

**Comment by dubisdev** [comment] 2022-09-13 10:26
I'm closing this as a duplicate of #115

**Closed by dubisdev** 2022-09-13 10:26 UTC
