### ISSUE TITLE
Couldn't the site on localhost[HELP]

### ISSUE THREAD

**Issue by sanjayk0508** [cerebroapp/cerebro#587] opened 2022-09-02 05:46 UTC
I have been trying to run the site on my local ide(terminal), but getting this error:
`[3964:0902/111238.030:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is ` 
pls help me out.

**Comment by dubisdev** [comment] 2022-09-02 08:56
Hi @sanjayk0508 

That's a normal electron error. Some computers just don't support some GPU optimizations.

I also get it but it doesn't break the app. Could you please answer this questions so we can reproduce de issue?

- What's your Operating System and version?

- What Cerebro version did you download? (You can get it from the executable name or typing `cerebro version` in Cerebro)

- What happens when you do `ctrl+space` with the program running?


Thanks 🙌
David

**Comment by sanjayk0508** [comment] 2022-09-02 09:26
- Operating System: Windows 10Pro 64-bit(10.0, Build 19044)
- I tried running` cerebro version ` in terminal & command, this is what it shows```
 'cerebro' is not recognized as an internal or external command,
operable program or batch file.
```
- Nothing is happing

For the context- I'm trying contribute nothing else.
I'm quite new to open source

**Comment by dubisdev** [comment] 2022-09-02 09:45
Okey, I assume you have cloned the repository.

Could you please run `yarn package`?

This should generate a `releases` fólder with executables for Windows.

Once installed and started, when using `ctrl+space` cerebro should show up.

Could you please try this and tell me What happens?

**Comment by dubisdev** [comment] 2022-11-09 11:47
I'm closing this as we cant reproduce the issue without information.

**Closed by dubisdev** 2022-11-09 11:47 UTC
