### ISSUE TITLE
Cerebro dosn't works in Ubuntu

### ISSUE THREAD

**Issue by Johan-Palacios** [cerebroapp/cerebro#539] opened 2021-07-04 18:54 UTC
I use Ubuntu 20.04.2 

And Cerebro doesn't works, i Installed the program 

![Captura de pantalla de 2021-07-04 12-52-34](https://user-images.githubusercontent.com/77251405/124396429-be57ea00-dcc6-11eb-988f-212af00ad1fe.png)

And i execute ctrl + space and cerebro dosn't works

**Comment by peng-chang** [comment] 2021-07-26 15:54
me too!

**Comment by Mohammed-Taher** [comment] 2021-08-08 07:27
I have the same issue. I have Ubuntu 20.04.2.

**Comment by 2br-2b** [comment] 2021-08-11 17:07
Duplicate of #527 

This seems like it should be fixed in the next update

**Comment by NigelThorne** [comment] 2021-10-30 10:10
![image](https://user-images.githubusercontent.com/5942/139528755-de955ae4-0d4d-4397-84b0-834159974dcd.png)
When I run the AppImage I get the following "Harfbuzz version too old (1.3.1)" error. 

Googling this error tends to end up at advice to get the developers to update their version of Atom. 
Does this mean that if new versions of Atom get onto my machine, older atom applications will die? 

Surely that's a bad design choice from Atom :(

Anyway... any advice to get your app started?

**Comment by imabp** [comment] 2022-01-08 05:35
I am still facing this error. Any workaround @oguhpereira

**Comment by NigelThorne** [comment] 2022-02-06 00:50
I got it installed some time ago. I'm sorry I forget the steps I took. I believe I ended up discovering the config was leading to the UI not showing up. I had to somehow change it to another theme, then it started working.

**Comment by dubisdev** [comment] 2022-09-16 14:53
I'm closing this as a duplicate of #527 , that has been already fixed.

**Closed by dubisdev** 2022-09-16 14:53 UTC
