### ISSUE TITLE
cannot start cerebro-0.3.1

### ISSUE THREAD

**Issue by h-b** [cerebroapp/cerebro#549] opened 2022-02-14 09:09 UTC
Hi,

on my system, the AppImage does not start with the following error:

```
$ ./cerebro-0.3.1-x86_64.AppImage 

(cerebro:95604): Pango-ERROR **: 09:47:05.038: Harfbuzz version too old (1.3.1)

[appimage-binfmt-bypass/bin] ERROR: child exited with code 5

```
Some details about my system:

```
Cerebro version:      0.3.1
Operating system:     Zorin OS 16
Ubuntu codename:      focal
Debian version:       bullseye/sid
Linux kernel version: 5.13.0-28-generic

$ dpkg -l | grep libpango
ii  libpango-1.0-0:amd64                                   1.44.7-2ubuntu4                             amd64        Layout and rendering of internationalized text
ii  libpango1.0-dev:amd64                                  1.44.7-2ubuntu4                             amd64        Development files for the Pango
ii  libpangocairo-1.0-0:amd64                              1.44.7-2ubuntu4                             amd64        Layout and rendering of internationalized text
ii  libpangoft2-1.0-0:amd64                                1.44.7-2ubuntu4                             amd64        Layout and rendering of internationalized text
ii  libpangomm-1.4-1v5:amd64                               2.42.0-2build1                              amd64        C++ Wrapper for pango (shared libraries)
ii  libpangoxft-1.0-0:amd64                                1.44.7-2ubuntu4                             amd64        Layout and rendering of internationalized text
$ dpkg -l | grep libharfbuzz
ii  libharfbuzz-dev:amd64                                  2.6.4-1ubuntu4                              amd64        Development files for OpenType text shaping engine
ii  libharfbuzz-gobject0:amd64                             2.6.4-1ubuntu4                              amd64        OpenType text shaping engine ICU backend (GObject library)
ii  libharfbuzz-icu0:amd64                                 2.6.4-1ubuntu4                              amd64        OpenType text shaping engine ICU backend
ii  libharfbuzz0b:amd64                                    2.6.4-1ubuntu4                              amd64        OpenType text shaping engine (shared library)
```

I am submitting this as a bug report because it is my understanding that if the AppImage format is used correctly, this error should not occur. Perhaps one of above libraries is accidentally not included in the AppImage.

Thank you
Stefan

**Comment by tivolimeister** [comment] 2022-03-04 13:00
Get the same. Also Zorin 16.

**Comment by oguhpereira** [comment] 2022-09-11 14:17
Hello try to use a newer brain version, it should work

**Comment by dubisdev** [comment] 2022-09-13 10:15
I'm closing this as a duplicate of #527

**Closed by dubisdev** 2022-09-13 10:15 UTC
