### ISSUE TITLE
Unable to start on Arch Linux

### ISSUE THREAD

**Issue by vishalbasnet23** [cerebroapp/cerebro#574] opened 2022-08-11 12:38 UTC
- [x] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: EndeavourOS Linux x86_64 
- **DE**: Budgie
- **Cerebro.app version**: [v0.6.0](
- **Relevant information from devtools** _(See above how to open it)_: N/A

## Issue
I tried to install Appimage downloaded from the site but after I make it executable and run, it throws me the following error:

installed: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9 image: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9
[1]    37830 segmentation fault (core dumped)  ./cerebro-0.3.1-x86_64.AppImage

**Comment by dubisdev** [comment] 2022-08-11 22:07
Hi @vishalbasnet23 

If you downloaded the package from website you probably downloaded an outdated version (the log shows you are using 0.3.1)

Try with
https://github.com/cerebroapp/cerebro/releases/download/v0.5.0/Cerebro-0.5.0.AppImage

The main branch is now in v0.6.0 but no executables were published. If you want you can try to build it from source following the instructions in the readme file.

Thanks 🙌
David

**Comment by dubisdev** [comment] 2022-08-13 17:26
With a different version but looks like a duplicate of #494

**Comment by dubisdev** [comment] 2022-09-13 10:33
I'm closing this as a duplicate of #494

**Closed by dubisdev** 2022-09-13 10:33 UTC
