### ISSUE TITLE
Error on Ubuntu 20.04

### ISSUE THREAD

**Issue by albertolaguna** [cerebroapp/cerebro#510] opened 2020-09-02 02:04 UTC
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 20.04
- **Cerebro.app version**: 0.3.2
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue
Is this still supported? I'm trying to install cerebro 0.3.2 on Ubuntu 20.04 with the AppImage and with the .deb file, but I have the next error when I execute: 

> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: ENOENT: no such file or directory, open '/home/alaguna/.config/Cerebro/config.json'
>     at Object.fs.openSync (fs.js:558:18)
>     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
>     at Object.fs.writeFileSync (fs.js:1233:33)
>     at Object.get (/opt/Cerebro/resources/app.asar/main.js:162:18)
>     at Object.module.exports.Object.defineProperty.value (/opt/Cerebro/resources/app.asar/main.js:642:24)
>     at __webpack_require__ (/opt/Cerebro/resources/app.asar/main.js:21:30)
>     at /opt/Cerebro/resources/app.asar/main.js:64:18
>     at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:67:10)
>     at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:3738:3)
>     at Module._compile (module.js:571:32)
> 
> (cerebro:8913): Pango-ERROR **: 20:51:53.530: Harfbuzz version too old (1.3.1)
> 
> Trace/breakpoint trap (core dumped)

I was googling for solutions, but nothing worked. Help me, please! I've not found any better alternative than cerebro

**Comment by ajithkumar-natarajan** [comment] 2020-09-10 23:22
It is the same as issue #505 and #501. The project is not being maintained and components need to be updated for the installation to work.

**Comment by pmarreck** [comment] 2020-09-23 14:42
The first mistake was writing this in Javascript which automatically incurs a dependency on the entire Node clusterfuck I MEAN ecosystem.

**Comment by MartinArens** [comment] 2020-12-02 11:49
Same Issue

**Comment by LucasE2996** [comment] 2021-03-17 15:54
Same Issue

**Comment by blahah** [comment] 2021-04-19 04:24
> The first mistake was writing this in Javascript which automatically incurs a dependency on the entire Node clusterf**k I MEAN ecosystem.

It really wasn't. The problem here is not to do with node, but poor dependency management in OS-level libs. That problem exists across all languages (and static compiling native libs for distribution across all modern platforms and hardware is a nightmare problem that is *only* solved well in the node ecosystem).

Sincerely,
Someone who's done this in 12 languages.

**Comment by pmarreck** [comment] 2021-04-22 01:26
@blahah You're right. I should not have let my frustration devolve into nonproductive ranting. Karma is a funny thing though, I'm actually dealing with what I think is a static vs. dynamic compilation bug *right now* and I'm not making great progress on it (alpine on docker, musl vs. glibc, etc.)

Cerebro looks really cool and I was just frustrated. Please accept my humble regret at earlier comment, and thank you for all your developer efforts.

**Comment by dubisdev** [comment] 2022-09-13 10:17
I'm closing this as a duplicate of #527

**Closed by dubisdev** 2022-09-13 10:17 UTC
