### ISSUE TITLE
(cerebro:16287): Pango-ERROR **: 14:40:42.230: Harfbuzz version too old (1.3.1)

### ISSUE THREAD

**Issue by markboston3502191** [cerebroapp/cerebro#505] opened 2020-05-21 18:48 UTC
- [ ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [ ] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Cerebro.app version**: 
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue
\\

this app does not load. the gui doesn't give me any type of error or anything. i ran it from the cli and i get this (cerebro:16287): Pango-ERROR **: 14:40:42.230: Harfbuzz version too old (1.3.1). i cannot give any logs or anything because it doesn't launch for me to be able to go into dev mode etc.

**Comment by kushgupta42** [comment] 2020-05-26 22:22
same issue happened with me 
(cerebro:29049): Pango-ERROR **: 03:50:36.126: Harfbuzz version too old (1.3.1) 
even after downgrading the version of cerebro , getting the same error

**Comment by Scupake** [comment] 2020-06-08 20:03
Same Issue

**Comment by rossdeane-awin** [comment] 2020-06-11 11:42
Duplicate of #501

**Comment by impiza** [comment] 2020-06-15 11:31
I am using Linux mint 20 now just upgraded from 19.3 
previously using deb file to install, and works perfectly fine, after upgrading it's not working, also used Appimage both failed.

**Comment by lfsabcd7** [comment] 2020-06-28 07:40
OS: Kali GNU/Linux Rolling x86_64 
     .....''''..........,:ld;                            Host: G3 3579 
           .';;;:::;,,.x,                               Kernel: 5.6.0-kali2-amd64 
      ..'''.            0Xxoc:,.  ...               Uptime: 2 hours, 7 mins 
  ....                ,ONkc;,;cokOdc',.            Packages: 3453 (dpkg), 9 (snap) 
 .                   OMo           ':ddo.          Shell: bash 5.0.16 
                    dMc               :OO;         Resolution: 1920x1080 
                    0M.                 .:o.       DE: GNOME 
                    ;Wd                            WM: Mutter 
                     ;XO,                          WM Theme: Kali-Dark 
                       ,d0Odlc;,..                 Theme: HighContrastInverse [GTK2/3] 
                           ..',;:cdOOd::,.         Icons: Flat-Remix-Blue-Dark [GTK2/3] 
                                    .:d;.':;.      Terminal: terminator 
                                       'd,  .'     CPU: Intel i7-8750H (12) @ 4.100GHz 
                                         ;l   ..   GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
                                          .o       GPU: Intel UHD Graphics 630 
                                            c      Memory: 4244MiB / 15939MiB 


same issue
installed: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9 image: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9

(cerebro:14638): Pango-ERROR **: 13:07:20.481: Harfbuzz version too old (1.3.1)

Trace/breakpoint trap

**Comment by ajithkumar-natarajan** [comment] 2020-08-15 20:11
Same here with Ubuntu 20.04.

**Comment by kirillt** [comment] 2020-11-12 06:19
Same issue on Fedora 32.

```
[kirill@lenovo ~]$ sudo dnf install harfbuzz
...
Package harfbuzz-2.6.4-3.fc32.x86_64 is already installed.
Package harfbuzz-2.6.4-3.fc32.i686 is already installed.
...
[kirill@lenovo cerebro]$ ./cerebro-0.3.1-x86_64.AppImage 
installed: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9 image: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9

(cerebro:2370100): Pango-ERROR **: 07:11:00.543: Harfbuzz version too old (1.3.1)

Trace/breakpoint trap (core dumped)
```

I can attach the core dump if anybody tell me where it is located.

**Comment by PersonalDavid** [comment] 2020-11-20 12:09
Same here (Mint 20):
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/cowboy/.config/Cerebro/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.get (/opt/Cerebro/resources/app.asar/main.js:162:18)
    at Object.module.exports.Object.defineProperty.value (/opt/Cerebro/resources/app.asar/main.js:642:24)
    at __webpack_require__ (/opt/Cerebro/resources/app.asar/main.js:21:30)
    at /opt/Cerebro/resources/app.asar/main.js:64:18
    at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:67:10)
    at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:3738:3)
    at Module._compile (module.js:571:32)

(cerebro:15467): Pango-ERROR **: 13:02:38.047: Harfbuzz version too old (1.3.1)

Trace/breakpoint trap (core dumped)
`

**Comment by PersonalDavid** [comment] 2020-11-20 12:18
Same here on Mint 20: 
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/cowboy/.config/Cerebro/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.get (/opt/Cerebro/resources/app.asar/main.js:162:18)
    at Object.module.exports.Object.defineProperty.value (/opt/Cerebro/resources/app.asar/main.js:642:24)
    at __webpack_require__ (/opt/Cerebro/resources/app.asar/main.js:21:30)
    at /opt/Cerebro/resources/app.asar/main.js:64:18
    at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:67:10)
    at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:3738:3)
    at Module._compile (module.js:571:32)

(cerebro:15467): Pango-ERROR **: 13:02:38.047: Harfbuzz version too old (1.3.1)

Trace/breakpoint trap (core dumped) 
```

**Comment by MartinArens** [comment] 2020-12-02 11:49
Same Issue

**Comment by uroojjj** [comment] 2020-12-13 19:48
Same issue here, trying to install cerebro.

**Comment by finnishbroccoli** [comment] 2021-02-02 16:46
Celebro application asked if I would like to integrate the appimage to desktop menu (or something like that), I selected yes.
Result

 ./cerebro-0.3.1-x86_64.AppImage 
Gtk-Message: 18:39:48.900: Failed to load module "xapp-gtk3-module"

(cerebro:5011): Pango-ERROR **: 18:39:49.607: Harfbuzz version too old (1.3.1)

Trace/breakpoint trap (core dumped)

**Comment by lordness4** [comment] 2021-02-19 11:18
Same error on OS: Ubuntu 20.04.2 LTS x86_64.

Is this still being developed? Has anyone found a working solution?

**Comment by oguhpereira** [comment] 2021-03-03 04:51
This error was happening because the electron version was too old. I believe this was resolved with the update

**Closed by oguhpereira** 2021-03-03 04:51 UTC

**Comment by vaurdan** [comment] 2021-03-09 19:53
@oguhpereira Hmm. Where is that latest version available? I can only find 0.3.2 and that one is from 2017...

**Comment by ajithkumar-natarajan** [comment] 2021-03-10 05:01
@vaurdan  The dependencies have been updated, which means you can download the source and build using yarn.

@oguhpereira  I did build but faced issues with Cerebro supporting only the basic functions of editing the Cerebro settings and exiting out of it. Couldn't even launch applications on my computer. Where is the package located after `yarn run package`? I am using Ubuntu.

**Comment by mmaldonadoemergya** [comment] 2021-06-16 14:27
In linux mint 20

A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/maikel/.config/Cerebro/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.get (/opt/Cerebro/resources/app.asar/main.js:162:18)
    at Object.module.exports.Object.defineProperty.value (/opt/Cerebro/resources/app.asar/main.js:642:24)
    at __webpack_require__ (/opt/Cerebro/resources/app.asar/main.js:21:30)
    at /opt/Cerebro/resources/app.asar/main.js:64:18
    at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:67:10)
    at Object.<anonymous> (/opt/Cerebro/resources/app.asar/main.js:3738:3)
    at Module._compile (module.js:571:32)
