### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by Pectojin** [cerebroapp/cerebro#399] opened 2017-10-21 13:50 UTC
- [X] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [X] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 17.04
- **Cerebro.app version**: 0.3.1
- **Relevant information from devtools**: strangely the issue doesn't result in any console output in the dev tools.

## Issue
Occasionally, when I activate Cerebro using the hotkeys, it will not render the "dropdrop" below the input field when I start typing. 
![screenshot_2017-10-21_15 31 01](https://user-images.githubusercontent.com/1561484/31852340-4801c490-b676-11e7-838d-58b59434acae.png)
From here I have to either go out of Cerebro or delete all the text in the input field and start over.

Applications will still open if I press enter and the Cerebro doesn't freeze. 

Nothing is output into the dev tools console when it happens, so I'm thinking it's something failing in the GTK libraries lying underneath the javascript. 

I have disabled all plugins, restarted Cerebro, and restarted my machine to test if it was maybe some temporary glitch but it seems to be fairly persistent. 

I'd say it probably happens every 10-30 times I toggle Cerebro.

**Comment by scmanjarrez** [comment] 2017-10-23 12:21
I also have this glitch.

- **OS version and name:** Ubuntu Gnome 16.04, gnome-shell 3.20.4.
- **Cerebro.app version:** 0.3.1

**Comment by Pectojin** [comment] 2017-10-23 17:26
I've had a chance to test this on a Macbook running High Sierra 10.13.1 today. I am completely unable to replicate the issue on MacOS.

So it seems this might be isolated to Linux.

**Comment by rcelha** [comment] 2017-11-07 10:29
@Pectojin upgrading electron helped me with this problem ... I'm not sure what the problem is though. It could be something related to hardware acceleration in Linux

**Comment by Pectojin** [comment] 2017-11-07 11:27
How did you upgrade electron? Isn't it bundled into the installer?

**Comment by rcelha** [comment] 2017-11-07 12:33
I ran from the repository

https://github.com/KELiON/cerebro#development

**Comment by assunluis80** [comment] 2018-02-06 09:28
This issue it's still happening in Debian Strecth (9.3) and Ubuntu Budgie 17.10. I followed the suggestion of @rcelha and compile it the newest electron release (1.7.2) but the issue persists.
![ubuntu_budgie_17 10](https://user-images.githubusercontent.com/8853276/35851501-22fad868-0b20-11e8-8bb8-6ce77d786a74.png)

**Comment by dubisdev** [comment] 2022-11-09 21:37
Hi all! I'm closing this issue as outdated (+5 years)

We have just released Cerebro `v0.9.0`. Give it a try and if the problem persists feel free to open a new issue in the repo.

**Closed** 2022-11-09 21:38 UTC
