### ISSUE TITLE
./cerebro-0.3.1-x86_64.AppImage 1st time execution crashing

### ISSUE THREAD

**Issue by Free-Radical** [cerebroapp/cerebro#571] opened 2022-08-08 03:09 UTC
- [x ] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [x ] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint 20.3
- **Cerebro.app version**: cerebro-0.3.1-x86_64.AppImage
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue
$ ./cerebro-0.3.1-x86_64.AppImage 
installed: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9 image: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9

(cerebro:25518): Pango-ERROR **: 22:03:19.453: Harfbuzz version too old (1.3.1)

Trace/breakpoint trap (core dumped)

**Comment by dubisdev** [comment] 2022-08-09 13:08
Hi @Free-Radical
 
Version 0.3.1 is outdated, this is a duplicated issue which was resolved in newer versions.

Try with
https://github.com/cerebroapp/cerebro/releases/download/v0.5.0/Cerebro-0.5.0.AppImage

The main branch is now in v0.6.0 but no executables were published. If you want you can try to build it from source following the instructions in the readme file.

Thanks 🙌
David

**Comment by dubisdev** [comment] 2022-09-13 10:15
I'm closing this as a duplicate of #527

**Closed by dubisdev** 2022-09-13 10:15 UTC
